name: CI

env:
  GOEXPERIMENT: jsonv2

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "release/**", "breaking/**"]

permissions:
  contents: read

concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  go-format:
    name: Go Format
    runs-on: depot-ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Setup Just
        uses: extractions/setup-just@v4

      - name: Check formatting
        run: |
          just format all
          git diff --exit-code -- .

  go-tests:
    name: Go Tests
    runs-on: depot-ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Just
        uses: extractions/setup-just@v4

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Download modules
        run: go mod download

      - name: Run unit tests
        run: just test

  go-linter:
    name: Go Linter
    runs-on: depot-ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: Run Golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: ./...
          only-new-issues: false
